version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ai-arena-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_arena
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ai-arena-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: